trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Listing all files and directories in the repository at all levels
    find .
  displayName: 'List all files in the repo recursively'
