trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Listing all files and directories in the repository at all levels
    find .
  displayName: 'List all files in the repo recursively'

- script: |
    echo Installing Python dependencies for each module
    for dep_file in $(find src -name 'local_dependencies.txt'); do
      echo "Installing dependencies from $dep_file"
      pip install -r $dep_file
    done
  displayName: 'Install Module Dependencies'

- script: |
    export PYTHONPATH=$(pwd):$PYTHONPATH
    echo "PYTHONPATH adjusted to: $PYTHONPATH"
  displayName: 'Set PYTHONPATH'

- script: |
    echo "Running unit tests for fridge_mgr"
    python -m unittest src/fridge_mgr/test/test_index.py -v
  displayName: 'Run fridge_mgr Test'
  condition: always()

- script: |
    echo "Running unit tests for health_report_mgr"
    python -m unittest src/health_report_mgr/test/test_index.py -v
  displayName: 'Run health_report_mgr Test'
  condition: always()

- script: |
    echo "Running unit tests for orders_mgr"
    python -m unittest src/orders_mgr/test/test_index.py -v
  displayName: 'Run orders_mgr Test'
  condition: always()

- script: |
    echo "Running unit tests for token_mgr"
    python -m unittest src/token_mgr/test/test_index.py -v
  displayName: 'Run token_mgr Test'
  condition: always()

- script: |
    echo "Running unit tests for update_orders"
    python -m unittest src/update_orders/test/test_index.py -v
  displayName: 'Run update_orders Test'
  condition: always()

- script: |
    echo "Running unit tests for users_mgr"
    python -m unittest src/users_mgr/test/test_index.py -v
  displayName: 'Run users_mgr Test'
  condition: always()

- script: |
    modules=("fridge_mgr" "health_report_mgr" "orders_mgr" "token_mgr" "update_orders" "users_mgr")
    for module in "${modules[@]}"
    do
      echo "Running unit tests for $module"
      python -m unittest src/$module/test/test_index.py -v
      if [ $? -ne 0 ]; then
        echo "Unit tests for $module failed"
        exit 1
      fi
    done
  displayName: 'Run Unit Tests for All Modules'
  condition: always()