trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Listing all files and directories in the repository at all levels
    find .
  displayName: 'List all files in the repo recursively'

- script: |
    echo Installing Python dependencies for each module
    for dep_file in $(find src -name 'local_dependencies.txt'); do
      echo "Installing dependencies from $dep_file"
      pip install -r $dep_file
    done
  displayName: 'Install Module Dependencies'

- script: |
    echo "Adjusting PYTHONPATH to include project src directory"
    export PYTHONPATH=$PYTHONPATH:$(pwd)/src
    echo "PYTHONPATH adjusted to: $PYTHONPATH"
  displayName: 'Adjust PYTHONPATH'

- script: |
    echo "Running a simple test for demonstration"
    python -m unittest src/fridge_mgr/test_index.py -v
  displayName: 'Run a Simple Test'

- script: |
    echo Finding and running tests for each Lambda function
    find src -path '*/test' -type d | while read test_dir; do
      for test_file in "$test_dir"/*test_index*.py; do
        if [ -f "$test_file" ]; then
          echo "Running tests in $test_file"
          python -m unittest "$test_file" -v
        else
          echo "No test files found in $test_dir"
        fi
      done
    done
  displayName: 'Run Lambda function tests'
