trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Listing all files and directories in the repository at all levels
    find .
  displayName: 'List all files in the repo recursively'

- script: |
    echo Adding project root to PYTHONPATH
    export PYTHONPATH=$PYTHONPATH:$(pwd)
    echo Finding and running tests for each Lambda function
    find . -path '*/src/*' -name 'index.py' | while read lambda_file; do
      test_file=$(echo "${lambda_file}" | sed 's|/src/index.py|/test/test_index.py|')
      echo "Running test for ${lambda_file}: ${test_file}"
      if [ -f "${test_file}" ]; then
        python -m unittest "${test_file}"
      else
        echo "Test file not found: ${test_file}"
      fi
    done
  displayName: 'Run Lambda function tests'

